import os
import json
import logging
import requests
from scipy.spatial.distance import cosine

# Setup logging if not already configured by the main app
logger = logging.getLogger(__name__)

def compare_vectors(vector_a: list, vector_b: list) -> float:
    """
    Computes the cosine similarity between two vectors.
    Cosine distance is between 0 and 1 where 0 means identical. 
    Subtract the result from 1 to get similarity where 1 means identical.
    """
    try:
        distance = cosine(vector_a, vector_b)
        similarity = 1.0 - distance
        return float(similarity)
    except (ValueError, ZeroDivisionError) as e:
        logger.error(f"Error computing cosine similarity: {e}")
        return 0.0

def check_intent(caption_text: str) -> dict:
    """
    Calls the Gemini API to determine if social media text indicates piracy or fair use.
    """
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        logger.warning("GEMINI_API_KEY environment variable is not set. Defaulting to PIRACY.")
        return {"intent": "PIRACY", "confidence_score": 0.5, "fallback": True}

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"
    
    prompt = (
        "You are a digital rights enforcement AI. Analyze the following social media caption "
        "and determine if it indicates unauthorized redistribution of copyrighted sports media "
        "or if it is legitimate fan commentary. A caption indicates piracy if it contains phrases "
        "suggesting free downloads, unofficial streams, sharing without permission, or explicit "
        "statements that no copyright is claimed to avoid detection. Legitimate fan use includes analysis, "
        "commentary, reactions, or discussion. Respond with only a JSON object with two fields: "
        "intent set to either the string PIRACY or the string FAIR_USE, and confidence_score "
        "set to a float between 0.0 and 1.0. Caption to analyze: " + caption_text
    )

    payload = {
        "contents": [{
            "parts": [{"text": prompt}]
        }],
        "generationConfig": {
            # Google's API typically uses camelCase, but we're matching the instruction.
            # We'll include both to be safe, though responseMimeType is the standard REST key.
            "responseMimeType": "application/json",
            "response_mime_type": "application/json"
        }
    }
    
    headers = {
        "Content-Type": "application/json"
    }

    try:
        response = requests.post(url, headers=headers, json=payload, timeout=10)
        
        # If the status code is not 200 OK, raise an exception
        response.raise_for_status()
        
        response_json = response.json()
        
        # Extract the text generated by Gemini
        text_content = response_json["candidates"][0]["content"]["parts"][0]["text"]
        
        # Parse the JSON string returned by Gemini
        parsed_result = json.loads(text_content)
        
        intent = parsed_result.get("intent", "PIRACY")
        
        # Enforce exactly formatting specified
        return {
            "intent": str(intent).strip().upper(),
            "confidence_score": float(parsed_result.get("confidence_score", 0.5))
        }

    except Exception as e:
        raw_response = None
        if 'response' in locals() and hasattr(response, 'text'):
            raw_response = response.text
        logger.warning(f"Failed to parse Gemini response for intent check. Error: {e}. Raw response: {raw_response}")
        return {"intent": "PIRACY", "confidence_score": 0.5, "fallback": True}
