import os
import json
import logging
import requests
import numpy as np
from scipy.spatial.distance import cosine

# Setup logging if not already configured by the main app
logger = logging.getLogger(__name__)

def compare_vectors(vector_a: list, vector_b: list) -> float:
    """
    Computes the cosine similarity between two vectors.
    Cosine distance is between 0 and 1 where 0 means identical. 
    Subtract the result from 1 to get similarity where 1 means identical.
    """
    try:
        distance = cosine(vector_a, vector_b)
        similarity = 1.0 - distance
        return float(similarity)
    except (ValueError, ZeroDivisionError) as e:
        logger.error(f"Error computing cosine similarity: {e}")
        return 0.0

def find_best_match(query_vector: list, vaulted_assets: list) -> tuple:
    """
    Finds the best match for a query vector against a list of vaulted assets
    using high-speed NumPy matrix operations.
    
    Args:
        query_vector: The 512D vector from the scraped video.
        vaulted_assets: List of Firestore DocumentSnapshots.
        
    Returns:
        tuple: (highest_similarity, matched_doc)
    """
    if not vaulted_assets:
        return 0.0, None

    try:
        # Convert query vector to a normalized numpy array
        q = np.array(query_vector)
        q_norm = np.linalg.norm(q)
        if q_norm == 0:
            return 0.0, None
        q = q / q_norm

        # Extract vectors from documents and keep track of valid ones
        doc_vectors = []
        valid_docs = []
        
        for doc in vaulted_assets:
            data = doc.to_dict()
            v = data.get("vector")
            if v and len(v) == 512:
                doc_vectors.append(v)
                valid_docs.append(doc)

        if not doc_vectors:
            return 0.0, None

        # Convert all vaulted vectors to a matrix: (N, 512)
        matrix = np.array(doc_vectors)
        
        # Normalize the matrix (row-wise)
        norms = np.linalg.norm(matrix, axis=1, keepdims=True)
        # Avoid division by zero
        norms[norms == 0] = 1.0
        matrix = matrix / norms

        # Batch Cosine Similarity = Matrix-Vector Multiplication: (N, 512) x (512,) = (N,)
        similarities = np.dot(matrix, q)

        # Find the index of the maximum similarity
        idx = np.argmax(similarities)
        highest_similarity = float(similarities[idx])
        matched_doc = valid_docs[idx]

        return highest_similarity, matched_doc

    except Exception as e:
        logger.error(f"Batch comparison failed: {e}")
        return 0.0, None

def check_intent(caption_text: str) -> dict:
    """
    Calls the Gemini API to determine if social media text indicates piracy or fair use.
    """
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        logger.warning("GEMINI_API_KEY environment variable is not set. Defaulting to PIRACY.")
        return {"intent": "PIRACY", "confidence_score": 0.5, "fallback": True}

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"
    
    prompt = (
        "You are a digital rights enforcement AI. Analyze the following social media caption "
        "and determine if it indicates unauthorized redistribution of copyrighted sports media "
        "or if it is legitimate fan commentary. A caption indicates piracy if it contains phrases "
        "suggesting free downloads, unofficial streams, sharing without permission, or explicit "
        "statements that no copyright is claimed to avoid detection. Legitimate fan use includes analysis, "
        "commentary, reactions, or discussion. Respond with only a JSON object with two fields: "
        "intent set to either the string PIRACY or the string FAIR_USE, and confidence_score "
        "set to a float between 0.0 and 1.0. Caption to analyze: " + caption_text
    )

    payload = {
        "contents": [{
            "parts": [{"text": prompt}]
        }],
        "generationConfig": {
            # Google's API typically uses camelCase, but we're matching the instruction.
            # We'll include both to be safe, though responseMimeType is the standard REST key.
            "responseMimeType": "application/json",
            "response_mime_type": "application/json"
        }
    }
    
    headers = {
        "Content-Type": "application/json"
    }

    try:
        response = requests.post(url, headers=headers, json=payload, timeout=10)
        
        # If the status code is not 200 OK, raise an exception
        response.raise_for_status()
        
        response_json = response.json()
        
        # Extract the text generated by Gemini
        text_content = response_json["candidates"][0]["content"]["parts"][0]["text"]
        
        # Parse the JSON string returned by Gemini
        parsed_result = json.loads(text_content)
        
        intent = parsed_result.get("intent", "PIRACY")
        
        # Enforce exactly formatting specified
        return {
            "intent": str(intent).strip().upper(),
            "confidence_score": float(parsed_result.get("confidence_score", 0.5))
        }

    except Exception as e:
        raw_response = None
        if 'response' in locals() and hasattr(response, 'text'):
            raw_response = response.text
        logger.warning(f"Failed to parse Gemini response for intent check. Error: {e}. Raw response: {raw_response}")
        return {"intent": "PIRACY", "confidence_score": 0.5, "fallback": True}
